version: "3.8"

services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  # Backend service 1 (3 replicas)
  backend_service1:
    build: ./backend/services/service1
    depends_on:
      - db
    networks:
      - app_network
    deploy:
      replicas: 3 # Scale backend service to 3 instances
      restart_policy:
        condition: on-failure

  # NGINX load balancer service
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80" # Expose NGINX to the host on port 80
    depends_on:
      - backend_service1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app_network

  # Interface service, interacts with NGINX
  interface:
    build: ./interface
    depends_on:
      - nginx
    ports:
      - "8080:8080" # Expose the interface to the host on port 8080
    networks:
      - app_network

# Define volumes
volumes:
  db_data:

# Define networks
networks:
  app_network:
    driver: bridge
